name: Security Scan Synk

on: [pull_request]

env:
  SNYK_TOKEN: ${{ secrets.SNYK_API_KEY }}

jobs:
  security:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Install Snyk
      run: npm install -g snyk

    - name: Snyk Auth
      run: snyk auth $SNYK_TOKEN

    - name: Snyk security scan
      run: snyk test

    - name: Snyk monitor
      run: snyk monitor